### ISSUE TITLE
Is this project can be used for more than one raw material supplier, one retailer, one manufacturer and one distributor? 

### ISSUE THREAD

**Issue by aniru-dh21** [faizack619/Supply-Chain-Blockchain#1]
Hey. I have a follow up here. So even though you register more than one Raw material suppliers ,Manufacturers, Distributors and Retailers, but trying follow up order those transactions are going through only the first registered Raw material suppliers ,Manufacturers, Distributors and Retailers. Is this the functionality of project of using only one registered user or I am making any mistake. Here are some photos for this follow up:
![screencapture-localhost-3000-roles-2023-11-17-18_51_21](https://github.com/Faizack/Supply-Chain-Blockchain/assets/75429046/3c4fe5cc-029d-4923-96f5-86f9f50c5533)
![screencapture-localhost-3000-addmed-2023-11-17-18_51_48](https://github.com/Faizack/Supply-Chain-Blockchain/assets/75429046/f5826847-0b0f-43c2-ae8a-300c07c7232a)
![screencapture-localhost-3000-track-2023-11-17-18_52_16](https://github.com/Faizack/Supply-Chain-Blockchain/assets/75429046/5f351cb3-615b-4114-bfd1-fecf01b1cab7)
![screencapture-localhost-3000-track-2023-11-17-18_52_34](https://github.com/Faizack/Supply-Chain-Blockchain/assets/75429046/a9496aad-37d7-4d86-9a66-70db706bd24e)

**Comment by faizack** [comment]
Yes
